services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      USERNAME: softplan
      PASSWORD: softplan123
      DB_URL: jdbc:h2:mem:testdb
      DB_DRIVER: org.h2.Driver
      DB_USERNAME: sa
      DB_PASSWORD: ""
      JPA_DDL_AUTO: create-drop
      JPA_DIALECT: org.hibernate.dialect.H2Dialect

  frontend:
    build:
      context: ./teste-softplan-web
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:8080/
    depends_on:
      - backend
